### PR TITLE
Fix black screen issue on boot

### PR DESCRIPTION
**Pull request by vinhtq115**
Added `enable-backlight-registers-fix` to fix black screen for 2-4 minutes after booting, which happens quite randomly.

From [WhateverGreen's boot arguments](https://github.com/acidanthera/WhateverGreen#boot-arguments):

> `-igfxblr` boot argument (and `enable-backlight-registers-fix` property) to fix backlight registers on KBL, CFL and ICL platforms.

### CODE REVIEW

**Comment by Juan-VC-gh** [comment]
Appreciate it, merged WEG black screen at boot fix

**Comment by 13thdemarch** [comment]
what does the black screen look like?
is it "dark" and cant increase brightness even the brightness level is maximum?

**Comment by vinhtq115** [comment]
> 
> 
> what does the black screen look like?
> is it "dark" and cant increase brightness even the brightness level is maximum?

I didn't take a closer look at it so idk.

**Comment by 13thdemarch** [comment]
> > what does the black screen look like?
> > is it "dark" and cant increase brightness even the brightness level is maximum?
> 
> I didn't take a closer look at it so idk.

okay thank you

**Comment by Juan-VC-gh** [comment]
It boots to a black screen randomly (even at full brightness), it is not common but happened. The solutions were restart or let it sleep and wake it

**Comment by Juan-VC-gh** [comment]
Mostly happened to me when i was on windows and immediately restarted to boot macOS

**Comment by 13thdemarch** [comment]
oh... so it is
i always restart if i met it.
btw when back from WIndows, the recommendation is shut down then power back. If restart, some drivers on Windows will affect to macOS

**Comment by Juan-VC-gh** [comment]
That could be what was causing the issue. Will shutdown then, thanks for the tip!

**Pull request merged**
